# Generated by Django 6.0.7 on 2026-09-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agenda_justificativa_alter_agenda_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
        ),
    ]
