# Generated by Django 6.0.7 on 2026-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_horarioatendimento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioatendimento',
            options={'ordering': ['dia_semana', 'inicio'], 'verbose_name': 'Horário de atendimento', 'verbose_name_plural': 'Horários de atendimento'},
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('SOLICITADO', 'AGENDADO', 'REALIZADO', 'BLOQUEADO'))), fields=('data', 'inicio'), name='agenda_horario_ativo_unico', violation_error_message='Já existe um agendamento ativo neste horário.'),
        ),
    ]
